"""Added setup complete bool to the user model

Revision ID: e8edcb876000
Revises: d49f53a5ce37
Create Date: 2025-06-03 10:30:13.298967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8edcb876000'
down_revision: Union[str, None] = 'd49f53a5ce37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
     # Step 1: Add the column with a temporary default (server-side)
    op.add_column('user', sa.Column('setup_complete', sa.Boolean(), nullable=True, server_default=sa.false()))

    # Step 2: Update existing rows to False
    op.execute('UPDATE "user" SET setup_complete = FALSE')

    # Step 3: Alter column to enforce NOT NULL
    op.alter_column('user', 'setup_complete', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'setup_complete')
    # ### end Alembic commands ###
